jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar o repositório
      uses: actions/checkout@v3

    - name: Instalar compilador GCC
      run: sudo apt update && sudo apt install build-essential -y

    - name: Compilar programa
      run: gcc -o teste soma.c teste.c

    - name: Rodar os testes
      run: ./teste

    - name: Executar testes automatizados
      run: |
        gcc -o teste teste.c
        ./teste



   
