name: CI para C

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar o repositório
      uses: actions/checkout@v3

    - name: Compile soma.c com testes
      run: gcc -o test soma.c test.c

    - name: Rodar os testes
      run: ./test
